[target.thumbv7em-none-eabihf]
runner = [
    "sh",
    "-c",
    "arm-none-eabi-objcopy -O binary $0 firmware.bin && dfu-util -a 0 -s 0x08000000 -D firmware.bin -R"
]

rustflags = [
    "-C", "link-arg=-Tlink.x"
]

[build]
target = "thumbv7em-none-eabihf"
