[target.thumbv7em-none-eabihf]
runner = [
    "sh",
    "-c",
    "python scripts/enter_bootloader.py && sleep 1 && arm-none-eabi-objcopy -O binary $0 firmware.bin && dfu-util -a 0 -s 0x08000000:leave -D firmware.bin"
]

rustflags = [
    "-C", "link-arg=-Tlink.x"
]

[build]
target = "thumbv7em-none-eabihf"
